return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 1,
  height = 1,
  tilewidth = 400,
  tileheight = 260,
  nextlayerid = 3,
  nextobjectid = 122,
  properties = {},
  tilesets = {
    {
      name = "map",
      firstgid = 1,
      filename = "map.tsx"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 1,
      height = 1,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        1
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "walls",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 82.0856,
          y = 41.5495,
          width = 5.06701,
          height = 126.169,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 87.1526,
          y = 160.371,
          width = 17.2278,
          height = 7.34717,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104.38,
          y = 160.371,
          width = 2.0268,
          height = 3.04021,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104.634,
          y = 166.705,
          width = 4.81366,
          height = 4.05361,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 79.8054,
          y = 168.225,
          width = 31.1621,
          height = 4.30696,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 70.4315,
          y = 165.185,
          width = 9.37397,
          height = 7.34717,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 70.4315,
          y = 165.185,
          width = 5.32036,
          height = 54.4704,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 75.7518,
          y = 210.788,
          width = 66.3778,
          height = 8.86727,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 134.782,
          y = 159.611,
          width = 7.34717,
          height = 51.1768,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 123.382,
          y = 159.611,
          width = 11.4008,
          height = 6.08041,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 125.409,
          y = 166.451,
          width = 8.36057,
          height = 3.80026,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 131.236,
          y = 172.025,
          width = 3.29356,
          height = 22.8016,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 131.236,
          y = 207.747,
          width = 5.32036,
          height = 8.10722,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 74.7384,
          y = 183.933,
          width = 8.36057,
          height = 16.2144,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 141.37,
          y = 212.308,
          width = 164.931,
          height = 6.84047,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 302.501,
          y = 163.918,
          width = 3.80026,
          height = 48.39,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 140.182,
          y = 139,
          width = 25.6364,
          height = 3.81818,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 162.091,
          y = 142.818,
          width = 3.72727,
          height = 31.9091,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 162.182,
          y = 174.273,
          width = 30.7273,
          height = 0.454545,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 185.909,
          y = 173,
          width = 7,
          height = 1.27273,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 163.364,
          y = 173.818,
          width = 29.4545,
          height = 3,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 186.182,
          y = 172.909,
          width = 6.90909,
          height = 39.6364,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 140,
          y = 141.25,
          width = 22.9375,
          height = 4.8125,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 158.188,
          y = 141.25,
          width = 4.8125,
          height = 32.75,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 162.688,
          y = 143.063,
          width = 14.0625,
          height = 3.875,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 165,
          y = 146.938,
          width = 10.875,
          height = 26.5625,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 175.875,
          y = 167.938,
          width = 12.9375,
          height = 5.5625,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 185.063,
          y = 166.938,
          width = 3.75,
          height = 1,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 160.25,
          width = 145.5,
          height = 99.75,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 124,
          y = 157.044,
          width = 15.4889,
          height = 2.48889,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 125.089,
          y = 156.022,
          width = 13.9556,
          height = 1.02222,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 123.111,
          y = 158.956,
          width = 1.17778,
          height = 1.28889,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 139,
          y = 157.063,
          width = 6.8125,
          height = 55.75,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 145.813,
          y = 174.875,
          width = 2,
          height = 37.9375,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 147.5,
          y = 207.063,
          width = 40.125,
          height = 5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160.063,
          y = 189.938,
          width = 19.75,
          height = 13.8125,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 179,
          y = 189.938,
          width = 0.375,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 161.188,
          y = 187.875,
          width = 17.8125,
          height = 2.0625,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 154.875,
          y = 189.188,
          width = 3.9375,
          height = 11.8125,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 158.5,
          y = 191.375,
          width = 5.6875,
          height = 6.625,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 157.063,
          y = 196.25,
          width = 5.4375,
          height = 2.5625,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 177.375,
          y = 189.375,
          width = 7.125,
          height = 8.25,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 242.625,
          y = 161.5,
          width = 15,
          height = 31.125,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256.375,
          y = 179.75,
          width = 4.875,
          height = 7.375,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 167.5,
          width = 5.5,
          height = 5.75,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 261.375,
          y = 180.125,
          width = 0.75,
          height = 5.375,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 238,
          y = 180,
          width = 5,
          height = 6.75,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 238.625,
          y = 166.75,
          width = 6.75,
          height = 6.75,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 246.25,
          y = 155.5,
          width = 7.25,
          height = 5.875,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 245.625,
          y = 192.25,
          width = 8.125,
          height = 5.75,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 266.5,
          y = 198,
          width = 10.75,
          height = 10.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 278.125,
          y = 198.125,
          width = 24.125,
          height = 15.75,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288.75,
          y = 166.25,
          width = 13.5,
          height = 31.875,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 274.875,
          y = 153.125,
          width = 5.375,
          height = 20.625,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280.25,
          y = 166.375,
          width = 12.75,
          height = 7.375,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 296.5,
          y = 164.375,
          width = 6.5,
          height = 5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 296.5,
          y = 149.5,
          width = 1.625,
          height = 14.875,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 305.25,
          y = 164.5,
          width = 100,
          height = 98,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 330.5,
          y = 151.25,
          width = 81.5,
          height = 13.75,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 329.75,
          y = 151,
          width = 2,
          height = 14.75,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 331,
          y = 79,
          width = 3,
          height = 72.75,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 293.75,
          y = 68.5,
          width = 117.5,
          height = 30.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 333,
          y = 67.75,
          width = 80,
          height = 98.75,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 305.75,
          y = 100.75,
          width = 14.25,
          height = 17.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 294.5,
          y = 95.75,
          width = 11.25,
          height = 23,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 261.25,
          y = 116,
          width = 33.25,
          height = 2.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 261,
          y = 118.5,
          width = 44.75,
          height = 1.75,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "rectangle",
          x = 296.125,
          y = 119.688,
          width = 2,
          height = 12.0625,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 273.25,
          y = 119.063,
          width = 19.8125,
          height = 8.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "rectangle",
          x = 291.75,
          y = 127.563,
          width = 1.3125,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 282.813,
          y = 127.063,
          width = 6.875,
          height = 3.875,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 329.273,
          y = 98.3636,
          width = 5.09091,
          height = 19.1818,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 329.455,
          y = 151.091,
          width = 4.54545,
          height = 18.8182,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 259,
          y = 34.875,
          width = 39.875,
          height = 44.125,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 260.75,
          y = 84.625,
          width = 15.625,
          height = 7,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 260.75,
          y = 84.625,
          width = 15.375,
          height = 9,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 284.125,
          y = 99.5,
          width = 10.75,
          height = 12.625,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "",
          shape = "rectangle",
          x = 259.125,
          y = 70.875,
          width = 5.375,
          height = 29.875,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 289.125,
          y = 93.375,
          width = 4.875,
          height = 5.125,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 209.5,
          y = 132.5,
          width = 42.75,
          height = 17.375,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 210.625,
          y = 104.75,
          width = 39,
          height = 9.125,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 94.625,
          width = 76.25,
          height = 5.375,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "",
          shape = "rectangle",
          x = 182.25,
          y = 97.125,
          width = 19.875,
          height = 15.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 177.25,
          y = 93.875,
          width = 7.625,
          height = 28.625,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 215.25,
          y = 86.5,
          width = 19.25,
          height = 7.625,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 210.5,
          y = 56.125,
          width = 28.125,
          height = 16.375,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 177.375,
          y = 43.375,
          width = 24,
          height = 20.125,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200.875,
          y = 43.375,
          width = 59,
          height = 4.75,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 244.375,
          y = 48.125,
          width = 13.625,
          height = 12.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 210.25,
          y = 46.125,
          width = 29.375,
          height = 6.125,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "rectangle",
          x = 239.25,
          y = 90.375,
          width = 15.25,
          height = 7,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 86.5,
          y = 156,
          width = 20.875,
          height = 5.125,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 86.5,
          y = 113.375,
          width = 6.25,
          height = 42.625,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 89,
          y = 116,
          width = 16.875,
          height = 34.625,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 89,
          y = 116,
          width = 18.375,
          height = 43.125,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 86.75,
          y = 42.75,
          width = 5.625,
          height = 73.375,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 86.75,
          y = 42.75,
          width = 94.375,
          height = 5.375,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "",
          shape = "rectangle",
          x = 156.625,
          y = 47.125,
          width = 14.5,
          height = 13.875,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 114.125,
          y = 46.75,
          width = 40.375,
          height = 46,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 97.375,
          y = 44,
          width = 14.25,
          height = 16.875,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 90.75,
          y = 83.5,
          width = 9.375,
          height = 21.25,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 122.875,
          y = 111.125,
          width = 18.875,
          height = 5.875,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "",
          shape = "rectangle",
          x = 140.5,
          y = 114.25,
          width = 6,
          height = 7.125,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 90.875,
          y = 114.25,
          width = 55.625,
          height = 7.125,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 118.125,
          width = 5.625,
          height = 3.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168.25,
          y = 115.125,
          width = 9.25,
          height = 8,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 177.125,
          y = 59.5,
          width = 6.375,
          height = 22.25,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 211.5,
          y = 200.75,
          width = 13.75,
          height = 10.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
